### PR TITLE
global: allow yaml schema files

### PR DESCRIPTION
**Pull request by david-caro**
* This will autogenerate the json files from any .yaml schema files at
  build time, allowing to use the more readable yaml format.

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by david-caro** [comment]
Of course, there aren't any yaml files yet to build here, but once we replace any .json with a .yaml, it will transparently do the transformation.

**Comment by david-caro** [comment]
Finally passing all the tests :), @michamos, you can base your pr on this one.

**Comment by michamos** [comment]
@david-caro Thanks, it is generating the JSON when running the tests but it is not prettified. Could you add a call to the prettifier?

**Comment by david-caro** [comment]
> @david-caro Thanks, it is generating the JSON when running the tests but it is not prettified. Could you add a call to the prettifier?

Where is that prettifier?

**Comment by david-caro** [comment]
Is `json.dumps(data, indent=4, sort_keys=True)` enough?

**Comment by david-caro** [comment]
@michamos Can you rebase again into this one and try again? Now the json output should be already pretty :)

**Comment by michamos** [comment]
I already fixed it in 633f392. Sorry for not letting you know.
Your gitignore changes are wrong, they are also ignoring the test fixtures.

**Comment by david-caro** [comment]
You should rebase at least on top of all but the last two commits then, there's a fix on the test script (it was looking for .yaml, but we use .yml for the files extension).

**Comment by jacquerie** [comment]
This was merged as part of #97.

**Pull request closed without merging**
