### PR TITLE
builders: fix unicode issues in LiteratureBuilder

### PR DESCRIPTION
**Pull request by michamos**

### CODE REVIEW

**Comment by drjova** [comment]
@michamos do we have to commit all resolved json?

**Comment by michamos** [comment]
whoops, my bad

**Comment by drjova** [comment]
shall we add it to .gitignore as well?

**Comment by michamos** [comment]
:+1: I'm already doing it

**Comment by michamos** [comment]
actually those were leftovers from previous code, so not needed.

**Pull request merged**
