### PR TITLE
Revert "elements: add thesis to degree_type"

### PR DESCRIPTION
**Pull request by kaplun**
This reverts commit 2b9decf26a0b5b060187aba334d1c1ab48f3da20.

### CODE REVIEW

**Comment by kaplun** [comment]
@spirosdelviniotis, as pointed me out by @michamos IRL, `thesis` should indeed map to `laurea`. So I am reverting this addition.

**Comment by michamos** [comment]
NO, `thesis` should map to `other` :smile:

**Comment by kaplun** [comment]
aaaaaaaaaaaagh. I need sleep :dancer:

**Comment by spirosdelviniotis** [comment]
OK

**Pull request merged**
