### PR TITLE
scripts: fix generate_example_records

### PR DESCRIPTION
**Pull request by jacquerie**
* Makes `scripts/generate_example_records.json` work out of the box
  by adding the proper requires and making it executable.

* Also adds `node_modules` to `.gitignore` so that we can `npm install
  json-schema-faker` locally.

Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>

### CODE REVIEW

**Comment by jacquerie** [comment]
@david-caro, thoughts?

**Comment by kaplun** [comment]
Oh! Why was this implemented in JS? (sorry not really related with this library but I am noticing it just now). There must be an equivalent library in Python.

**Comment by kaplun** [comment]
E.g. https://pypi.python.org/pypi/fake-factory

**Comment by jacquerie** [comment]
> E.g. https://pypi.python.org/pypi/fake-factory

This is missing the JSON Schema part. Here's a relevant issue: https://github.com/Julian/jsonschema/issues/259

Maybe add an issue about this, just to add it to the record.

**Comment by david-caro** [comment]
this looks ok for me, I did it in json because I did not find a nice library for python that did it, even with the json one, I was unable to really get the full examples from the default api... this small js script took me half an evening (did not want to spend much time as this was blocking a bunch of other things).

Open to any suggestion :)

**Comment by kaplun** [comment]
Looks like there's no python JSONSchema object generator. So indeed what you did was the most practical thing :+1:

**Pull request merged**
