### PR TITLE
hep: add missing signature_block

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

### CODE REVIEW

**Comment by kaplun** [comment]
@michamos I am sorry for this new field. But it's really a stupid one and need for the deployment.

**Comment by michamos** [comment]
how come this was not caught on QA?

**Comment by kaplun** [comment]
Because beard is very likely disabled on QA

**Comment by kaplun** [comment]
Or it is on Travis.

**Comment by kaplun** [comment]
Mmh. it's actually enabled on QA. So... no clue for the moment.

**Comment by kaplun** [comment]
Right now though, QA has only those records that have no authors (hence no `signature_block`).

**Comment by jacquerie** [comment]
This should have been schema 31. In fact, schema 30 are already broken, because they miss something like #123 (which is not ready to merge) to fix the failures in https://travis-ci.org/inspirehep/inspire-next/builds/211913781.

**Comment by michamos** [comment]
You shoud have regenerated the fixtures as well.

**Comment by kaplun** [comment]
I know, but it was late in the night... :dancing_women:

**Pull request merged**
