### PR TITLE
schemas: add missing types

### PR DESCRIPTION
**Pull request by kaplun**
Signed-off-by: Jacopo Notarstefano <jacopo.notarstefano@cern.ch>
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>

(closes #16)

### CODE REVIEW

**Comment by kaplun** [comment]
I have completed @jacquerie work using the `domapping` trick.

I.e.:
```
domapping schema_to_mapping hep.json
```

and so on.

**Comment by jmartinm** [comment]
Ready to merge it seems? Can you rebase and merge this? Will make the record editor happy.

**Comment by jacquerie** [comment]
What is the "`domapping` trick"?

**Comment by kaplun** [comment]
If you install invenio's domapping package that you can simply execute the above command on any schema and it will stop at the first error :+1: (more or less, it has some problems resolving our nested schemas though).

**Pull request merged**
