### PR TITLE
builders.LiteratureBuilder: add pubinfo_freetext

### PR DESCRIPTION
**Pull request by david-caro**
* We were missing the pubinfo_freetext from the publication_info.

Signed-off-by: David Caro <david@dcaro.es>

### CODE REVIEW

**Comment by michamos** [comment]
The freetext is a legacy thing that should not be populated anymore. Why is
this needed?

Il 20 mar 2017 8:43 PM, "David Caro" <notifications@github.com> ha scritto:

**Comment by david-caro** [comment]
it's in the schema, so I thought it was still needed. From the crawler is the only thing we are actually populating right now (in the publication_info entry).
If that's not needed anymore, I can just completely ignore the publication info.

**Comment by michamos** [comment]
Wait, publication _nfo is needed, only the freetext part is not. Cannot hepcrawl build a proper publication_info?

**Comment by david-caro** [comment]
It's done by refextract... that runs at the end in legacy (as the one in labs is supposedly not yet ready)

**Comment by michamos** [comment]
That sounds a bit crazy, but anyhow, this is not a blocker for deploying, right?

**Comment by david-caro** [comment]
Kindof, as the crawling needs this, and the crawling is needed for the deploy

**Comment by david-caro** [comment]
Sorry, it's done in the workflow before sending to legacy if I'm not mistaken

**Pull request merged**
